import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";
import { useState } from "react";
import { appRouter } from "~/server/api/root";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const createBuildMutation = api.builds.createBuild.useMutation();
  const [matchUp, setMatchUp] = useState("");
  const [build, setBuildOrder] = useState("");

  const router = useRouter();

  async function handleSubmitBuildOrder(e: React.FormEvent) {
    e.preventDefault();
    await createBuildMutation.mutateAsync({
      matchUp,
      build,
    });
    router.push("/");
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center gap-8 bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white">
        <h1>Welcome to SC2 Build Order Manager</h1>
        <Link href="/submit-build">Submit a new Build</Link>
      </main>
    </>
  );
};

export default Home;
